### ISSUE TITLE
Support for Python 3.7

### ISSUE THREAD

**Issue by giswqs** [aazuspan/eerepr#15]
I am trying to integrate eerepr into geemap. Just noticed that eerepr requires Python >=3.8. Any reason why Python 3.7 is not supported? Since Colab still uses Python 3.7, although I can use `pip install eerepr --ignore-requires-python` to install it,  it is not ideal as a dependency for other packages.

**Comment by aazuspan** [comment]
Hi @giswqs, I was hoping to avoid supporting 3.7 since the [Numpy support schedule](https://numpy.org/neps/nep-0029-deprecation_policy.html) recommended dropping it a year ago, but since Colab is still stuck on it and this is the  second request (see #13), I'll break down and add support with the next release. I'll keep you posted.
